const palette = {
  blue: '#4A90D9',
  blueDark: '#3A7BC8',
  blueLight: '#E6F0FA',
  green: '#34C759',
  greenLight: '#E8F9ED',
  orange: '#FF9500',
  orangeLight: '#FFF3E0',
  red: '#FF3B30',
  redLight: '#FFEBEE',
  secondary: '#7C5CFC',
  secondaryLight: '#EDE8FF',
  ambre: '#F5A623',
  ambreLight: '#FFF8E1',
  greenRich: '#2ECC71',
  greenRichLight: '#E8F8F0',
  gray50: '#FAFAFA',
  gray100: '#F5F5F5',
  gray200: '#EEEEEE',
  gray300: '#E0E0E0',
  gray400: '#BDBDBD',
  gray500: '#9E9E9E',
  gray600: '#757575',
  gray700: '#616161',
  gray800: '#424242',
  gray900: '#212121',
  white: '#FFFFFF',
  black: '#000000',
};

export const masteryColors = {
  unknown: palette.gray500,
  fragile: palette.ambre,
  ok: palette.blue,
  solid: palette.greenRich,
};

export default {
  palette,
  light: {
    text: palette.gray900,
    textSecondary: palette.gray600,
    background: palette.white,
    backgroundSecondary: palette.gray50,
    card: palette.white,
    border: palette.gray200,
    tint: palette.blue,
    tintLight: palette.blueLight,
    tabIconDefault: palette.gray400,
    tabIconSelected: palette.blue,
    success: palette.green,
    successLight: palette.greenLight,
    warning: palette.orange,
    warningLight: palette.orangeLight,
    error: palette.red,
    errorLight: palette.redLight,
  },
  dark: {
    text: palette.white,
    textSecondary: palette.gray400,
    background: palette.gray900,
    backgroundSecondary: palette.black,
    card: palette.gray800,
    border: palette.gray700,
    tint: palette.blue,
    tintLight: '#1A3A5C',
    tabIconDefault: palette.gray500,
    tabIconSelected: palette.blue,
    success: palette.green,
    successLight: '#1A3A2A',
    warning: palette.orange,
    warningLight: '#3A2A1A',
    error: palette.red,
    errorLight: '#3A1A1A',
  },
};
