package app

import (
	"encoding/json"
	"fmt"
	"strings"
)

// Feedback contains the 3 mandatory elements per Z4-AC09.
type Feedback struct {
	CorrectAnswer  string `json:"correct_answer"`
	WhatWasMissing string `json:"what_was_missing"`
	Hint           string `json:"hint"`
}

// GenerateFeedback creates enriched feedback based on template type.
// Generated by template (not LLM) for consistency and speed (< 200ms).
func GenerateFeedback(templateID string, expectedAnswer, studentAnswer []byte) Feedback {
	switch {
	case strings.Contains(templateID, "CLOZE_KEYWORDS"):
		return generateKeywordsFeedback(expectedAnswer, studentAnswer)
	case strings.Contains(templateID, "FLASH_MCQ"):
		return generateMCQFeedback(expectedAnswer, studentAnswer)
	case strings.Contains(templateID, "DEF_SHORT"):
		return generateShortAnswerFeedback(expectedAnswer, studentAnswer)
	default:
		return generateGenericFeedback(expectedAnswer)
	}
}

func generateKeywordsFeedback(expectedAnswer, _ []byte) Feedback {
	var expected struct {
		Keywords []string `json:"keywords"`
	}
	json.Unmarshal(expectedAnswer, &expected)

	return Feedback{
		CorrectAnswer:  fmt.Sprintf("Les mots-clés attendus étaient : %s", strings.Join(expected.Keywords, ", ")),
		WhatWasMissing: fmt.Sprintf("Mots-clés manquants : %s", strings.Join(expected.Keywords, ", ")),
		Hint:           fmt.Sprintf("Retiens les termes essentiels : %s.", strings.Join(expected.Keywords, ", ")),
	}
}

func generateMCQFeedback(expectedAnswer, _ []byte) Feedback {
	var expected struct {
		Correct     string `json:"correct"`
		Explanation string `json:"explanation"`
	}
	json.Unmarshal(expectedAnswer, &expected)

	return Feedback{
		CorrectAnswer:  fmt.Sprintf("La bonne réponse était : %s", expected.Correct),
		WhatWasMissing: expected.Explanation,
		Hint:           expected.Explanation,
	}
}

func generateShortAnswerFeedback(expectedAnswer, _ []byte) Feedback {
	var expected struct {
		Answer string `json:"answer"`
	}
	json.Unmarshal(expectedAnswer, &expected)

	return Feedback{
		CorrectAnswer:  fmt.Sprintf("La réponse attendue était : %s", expected.Answer),
		WhatWasMissing: "Ta réponse ne contenait pas les éléments clés attendus.",
		Hint:           "Relis la définition dans ta leçon pour retrouver les termes exacts.",
	}
}

func generateGenericFeedback(expectedAnswer []byte) Feedback {
	return Feedback{
		CorrectAnswer:  string(expectedAnswer),
		WhatWasMissing: "Certains éléments de la réponse étaient manquants ou incorrects.",
		Hint:           "Revois cette notion dans ta carte de leçon.",
	}
}
