package app

import (
	"encoding/json"
	"fmt"
	"strings"
)

// Feedback contains the 3 mandatory elements per Z4-AC09.
type Feedback struct {
	CorrectAnswer  string `json:"correct_answer"`
	WhatWasMissing string `json:"what_was_missing"`
	Hint           string `json:"hint"`
}

// GenerateFeedback creates enriched feedback based on template type.
// Generated by template (not LLM) for consistency and speed (< 200ms).
func GenerateFeedback(templateID string, expectedAnswer, studentAnswer []byte) Feedback {
	switch {
	case strings.Contains(templateID, "CLOZE_KEYWORDS"):
		return generateKeywordsFeedback(expectedAnswer, studentAnswer)
	case strings.Contains(templateID, "FLASH_MCQ"):
		return generateMCQFeedback(expectedAnswer, studentAnswer)
	case strings.Contains(templateID, "DEF_SHORT"):
		return generateShortAnswerFeedback(expectedAnswer, studentAnswer)
	default:
		return generateGenericFeedback(expectedAnswer)
	}
}

func generateKeywordsFeedback(expectedAnswer, _ []byte) Feedback {
	var expected struct {
		Answer       string   `json:"answer"`
		Keywords     string   `json:"keywords"`
		KeywordsList []string `json:"keywords_list"`
	}
	json.Unmarshal(expectedAnswer, &expected)

	// keywords can be a comma-separated string or a list
	kw := expected.Keywords
	if kw == "" && len(expected.KeywordsList) > 0 {
		kw = strings.Join(expected.KeywordsList, ", ")
	}
	answer := expected.Answer
	if answer == "" {
		answer = kw
	}

	return Feedback{
		CorrectAnswer:  fmt.Sprintf("La réponse attendue était : %s", answer),
		WhatWasMissing: fmt.Sprintf("Mots-clés attendus : %s", kw),
		Hint:           fmt.Sprintf("Retiens les termes essentiels : %s.", kw),
	}
}

func generateMCQFeedback(expectedAnswer, _ []byte) Feedback {
	var expected struct {
		Answer      string `json:"answer"`
		Correct     string `json:"correct"`
		Explanation string `json:"explanation"`
	}
	json.Unmarshal(expectedAnswer, &expected)

	// Support both "answer" and "correct" fields
	correctValue := expected.Correct
	if correctValue == "" {
		correctValue = expected.Answer
	}
	explanation := expected.Explanation
	if explanation == "" {
		explanation = "Revois cette notion dans ta carte de leçon."
	}

	return Feedback{
		CorrectAnswer:  fmt.Sprintf("La bonne réponse était : %s", correctValue),
		WhatWasMissing: explanation,
		Hint:           explanation,
	}
}

func generateShortAnswerFeedback(expectedAnswer, _ []byte) Feedback {
	var expected struct {
		Answer string `json:"answer"`
	}
	json.Unmarshal(expectedAnswer, &expected)

	return Feedback{
		CorrectAnswer:  fmt.Sprintf("La réponse attendue était : %s", expected.Answer),
		WhatWasMissing: "Ta réponse ne contenait pas les éléments clés attendus.",
		Hint:           "Relis la définition dans ta leçon pour retrouver les termes exacts.",
	}
}

func generateGenericFeedback(expectedAnswer []byte) Feedback {
	return Feedback{
		CorrectAnswer:  string(expectedAnswer),
		WhatWasMissing: "Certains éléments de la réponse étaient manquants ou incorrects.",
		Hint:           "Revois cette notion dans ta carte de leçon.",
	}
}
