package main

import (
	"context"
	"log"
	"net/http"
	"os"
	"os/signal"
	"syscall"
	"time"

	"github.com/gin-gonic/gin"

	"github.com/popul/revisemieux/internal/app"
	"github.com/popul/revisemieux/internal/config"
	"github.com/popul/revisemieux/internal/db"
	"github.com/popul/revisemieux/internal/domain/chapter"
	"github.com/popul/revisemieux/internal/domain/event"
	apphttp "github.com/popul/revisemieux/internal/http"
	"github.com/popul/revisemieux/internal/http/handler"
	llmanthro "github.com/popul/revisemieux/internal/infra/anthropic"
	"github.com/popul/revisemieux/internal/infra/openaicompat"
	"github.com/popul/revisemieux/internal/infra/eventbus"
	"github.com/popul/revisemieux/internal/infra/postgres"

	// Swagger docs — generated by swag init
	_ "github.com/popul/revisemieux/internal/docs"
)

// Version is set at build time via -ldflags.
var Version = "dev"

// @title           Révise Mieux API
// @version         0.1.0
// @description     API backend pour Révise Mieux — assistant de révision pour collégiens.
//
// @host            localhost:8080
// @BasePath        /api/v1
//
// @securityDefinitions.apikey BearerAuth
// @in                         header
// @name                       Authorization
// @description                JWT Bearer token (ex: "Bearer eyJhbGci...")

func main() {
	cfg := config.MustLoad()
	gin.SetMode(cfg.GinMode)

	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()

	// --- Database ---
	pool, err := db.NewPool(ctx, cfg.DatabaseURL)
	if err != nil {
		log.Fatalf("Database connection failed: %v", err)
	}
	defer pool.Close()

	// --- Run migrations ---
	if err := db.Migrate(ctx, pool, cfg.MigrationsDir); err != nil {
		log.Fatalf("Migrations failed: %v", err)
	}

	// --- Infrastructure ---
	clock := event.RealClock{}
	idGen := event.UUIDv7Generator{}
	publisher := eventbus.NewLogPublisher()

	// --- Repositories ---
	chapterRepo := postgres.NewChapterRepository(pool)
	masteryRepo := postgres.NewMasteryRepository(pool)
	sessionRepo := postgres.NewSessionRepository(pool)
	validationRepo := postgres.NewValidationRepository(pool)

	// --- LLM Service ---
	var llmStructurer chapter.LLMService
	switch cfg.LLMProvider {
	case "anthropic":
		if cfg.AnthropicAPIKey != "" {
			llmStructurer = llmanthro.NewStructurer(cfg.AnthropicAPIKey, cfg.AnthropicStructModel)
			log.Printf("LLM structurer initialized: provider=anthropic model=%s", cfg.AnthropicStructModel)
		} else {
			log.Println("WARNING: ANTHROPIC_API_KEY not set — LLM structuration disabled")
		}
	case "gemini":
		if cfg.GoogleAIAPIKey != "" {
			llmStructurer = openaicompat.NewStructurer(
				"https://generativelanguage.googleapis.com/v1beta/openai",
				cfg.GoogleAIAPIKey,
				cfg.GeminiStructModel,
			)
			log.Printf("LLM structurer initialized: provider=gemini model=%s", cfg.GeminiStructModel)
		} else {
			log.Println("WARNING: GOOGLE_AI_API_KEY not set — LLM structuration disabled")
		}
	default:
		log.Printf("WARNING: unknown LLM_PROVIDER %q — LLM structuration disabled", cfg.LLMProvider)
	}
	// PipelineService requires Storage + OCR adapters (not yet implemented).
	// When ready, wire: app.NewPipelineService(chapterRepo, masteryRepo, storage, ocr, llmStructurer, publisher, clock, idGen)
	_ = llmStructurer

	// --- Application Services ---
	chapterSvc := app.NewChapterService(chapterRepo)
	masterySvc := app.NewMasteryService(masteryRepo, publisher, clock)
	sessionSvc := app.NewSessionService(sessionRepo, chapterRepo, masteryRepo, publisher, clock, idGen)
	validationSvc := app.NewValidationService(validationRepo, chapterRepo, publisher, clock, idGen)
	onboardingSvc := app.NewOnboardingService(chapterRepo, masteryRepo, clock, idGen)

	// --- HTTP Handlers ---
	chapterHandler := handler.NewChapter(chapterSvc, chapterRepo, idGen, clock)
	masteryHandler := handler.NewMastery(masterySvc)
	sessionHandler := handler.NewSession(sessionSvc)
	validationHandler := handler.NewValidation(validationSvc)
	onboardingHandler := handler.NewOnboarding(onboardingSvc)

	// --- Router ---
	r := apphttp.NewRouter(apphttp.RouterConfig{
		JWTSecret:         cfg.JWTSecret,
		Version:           Version,
		ChapterHandler:    chapterHandler,
		MasteryHandler:    masteryHandler,
		SessionHandler:    sessionHandler,
		ValidationHandler: validationHandler,
		OnboardingHandler: onboardingHandler,
	})

	// --- HTTP server with graceful shutdown ---
	srv := &http.Server{
		Addr:    ":" + cfg.Port,
		Handler: r,
	}

	go func() {
		sigCh := make(chan os.Signal, 1)
		signal.Notify(sigCh, syscall.SIGINT, syscall.SIGTERM)
		<-sigCh
		log.Println("Shutting down...")

		shutdownCtx, shutdownCancel := context.WithTimeout(context.Background(), 10*time.Second)
		defer shutdownCancel()

		if err := srv.Shutdown(shutdownCtx); err != nil {
			log.Printf("HTTP server shutdown error: %v", err)
		}
		cancel()
	}()

	log.Printf("Starting Révise Mieux API on :%s (version %s)", cfg.Port, Version)
	if err := srv.ListenAndServe(); err != nil && err != http.ErrServerClosed {
		log.Fatalf("Server error: %v", err)
	}
}
