package main

import (
	"context"
	"log"
	"net/http"
	"os"
	"os/signal"
	"syscall"
	"time"

	"github.com/gin-gonic/gin"

	"github.com/popul/revisemieux/internal/app"
	"github.com/popul/revisemieux/internal/config"
	"github.com/popul/revisemieux/internal/db"
	"github.com/popul/revisemieux/internal/domain/chapter"
	"github.com/popul/revisemieux/internal/domain/event"
	"github.com/popul/revisemieux/internal/domain/session"
	apphttp "github.com/popul/revisemieux/internal/http"
	"github.com/popul/revisemieux/internal/http/handler"
	llmanthro "github.com/popul/revisemieux/internal/infra/anthropic"
	"github.com/popul/revisemieux/internal/infra/eventbus"
	"github.com/popul/revisemieux/internal/infra/ocr"
	"github.com/popul/revisemieux/internal/infra/openaicompat"
	"github.com/popul/revisemieux/internal/infra/postgres"
	"github.com/popul/revisemieux/internal/infra/s3"

	// Swagger docs — generated by swag init
	_ "github.com/popul/revisemieux/internal/docs"
)

// Version is set at build time via -ldflags.
var Version = "dev"

// @title           Révise Mieux API
// @version         0.1.0
// @description     API backend pour Révise Mieux — assistant de révision pour collégiens.
//
// @host            localhost:8080
// @BasePath        /api/v1
//
// @securityDefinitions.apikey BearerAuth
// @in                         header
// @name                       Authorization
// @description                JWT Bearer token (ex: "Bearer eyJhbGci...")

func main() {
	cfg := config.MustLoad()
	gin.SetMode(cfg.GinMode)

	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()

	// --- Database ---
	pool, err := db.NewPool(ctx, cfg.DatabaseURL)
	if err != nil {
		log.Fatalf("Database connection failed: %v", err)
	}
	defer pool.Close()

	// --- Run migrations ---
	if err := db.Migrate(ctx, pool, cfg.MigrationsDir); err != nil {
		log.Fatalf("Migrations failed: %v", err)
	}

	// --- Infrastructure ---
	clock := event.RealClock{}
	idGen := event.UUIDv7Generator{}
	dispatcher := eventbus.NewSyncDispatcher()
	var publisher event.Publisher = dispatcher

	// --- LLM Call Logger ---
	llmLogger := postgres.NewLLMCallLogger(pool)
	_ = llmLogger // TODO: pass to LLM clients for instrumentation
	log.Println("LLM call logger initialized")

	// --- Repositories ---
	chapterRepo := postgres.NewChapterRepository(pool)
	masteryRepo := postgres.NewMasteryRepository(pool)
	sessionRepo := postgres.NewSessionRepository(pool)
	validationRepo := postgres.NewValidationRepository(pool)

	// --- LLM Service ---
	var llmStructurer chapter.LLMService
	switch cfg.LLMProvider {
	case "anthropic":
		if cfg.AnthropicAPIKey != "" {
			llmStructurer = llmanthro.NewStructurer(cfg.AnthropicAPIKey, cfg.AnthropicStructModel)
			log.Printf("LLM structurer initialized: provider=anthropic model=%s", cfg.AnthropicStructModel)
		} else {
			log.Println("WARNING: ANTHROPIC_API_KEY not set — LLM structuration disabled")
		}
	case "gemini":
		if cfg.GoogleAIAPIKey != "" {
			llmStructurer = openaicompat.NewStructurer(
				"https://generativelanguage.googleapis.com/v1beta/openai",
				cfg.GoogleAIAPIKey,
				cfg.GeminiStructModel,
			)
			log.Printf("LLM structurer initialized: provider=gemini model=%s", cfg.GeminiStructModel)
		} else {
			log.Println("WARNING: GOOGLE_AI_API_KEY not set — LLM structuration disabled")
		}
	case "mistral":
		if cfg.MistralAPIKey != "" {
			llmStructurer = openaicompat.NewStructurer(
				"https://api.mistral.ai/v1",
				cfg.MistralAPIKey,
				cfg.MistralStructModel,
			)
			log.Printf("LLM structurer initialized: provider=mistral model=%s", cfg.MistralStructModel)
		} else {
			log.Println("WARNING: MISTRAL_API_KEY not set — LLM structuration disabled")
		}
	case "lmstudio":
		llmStructurer = openaicompat.NewStructurer(
			cfg.LMStudioBaseURL,
			"lm-studio",
			cfg.LMStudioStructModel,
		)
		log.Printf("LLM structurer initialized: provider=lmstudio model=%s", cfg.LMStudioStructModel)
	default:
		log.Printf("WARNING: unknown LLM_PROVIDER %q — LLM structuration disabled", cfg.LLMProvider)
	}
	// --- Storage (S3/MinIO) ---
	var storage chapter.Storage
	if cfg.S3AccessKey != "" && cfg.S3SecretKey != "" {
		s3Storage, err := s3.New(s3.Config{
			Endpoint:  cfg.S3Endpoint,
			AccessKey: cfg.S3AccessKey,
			SecretKey: cfg.S3SecretKey,
			Bucket:    cfg.S3Bucket,
			Region:    cfg.S3Region,
		})
		if err != nil {
			log.Printf("WARNING: S3/MinIO init failed: %v — pipeline disabled", err)
		} else {
			storage = s3Storage
			log.Printf("S3 storage initialized: endpoint=%s bucket=%s", cfg.S3Endpoint, cfg.S3Bucket)
		}
	} else {
		log.Println("WARNING: S3_ACCESS_KEY/S3_SECRET_KEY not set — pipeline disabled")
	}

	// --- OCR Service ---
	var ocrService chapter.OCRService
	switch cfg.LLMProvider {
	case "lmstudio":
		ocrService = ocr.NewGeminiOCR(ocr.Config{
			BaseURL: cfg.LMStudioBaseURL,
			APIKey:  "lm-studio",
			Model:   cfg.LMStudioOCRModel,
		})
		log.Printf("OCR service initialized: provider=lmstudio model=%s", cfg.LMStudioOCRModel)
	default:
		if cfg.GoogleAIAPIKey != "" {
			ocrService = ocr.NewGeminiOCR(ocr.Config{
				APIKey: cfg.GoogleAIAPIKey,
			})
			log.Println("OCR service initialized: provider=gemini-flash-vlm")
		} else {
			log.Println("WARNING: GOOGLE_AI_API_KEY not set — OCR disabled")
		}
	}

	// --- PipelineService (wired only if all dependencies available) ---
	var pipelineSvc *app.PipelineService
	if storage != nil && ocrService != nil && llmStructurer != nil {
		pipelineSvc = app.NewPipelineService(chapterRepo, masteryRepo, storage, ocrService, llmStructurer, publisher, clock, idGen)
		log.Println("PipelineService initialized (upload + OCR + structuration)")
	} else {
		log.Println("WARNING: PipelineService not available (missing storage, OCR, or LLM)")
	}

	// --- Answer Scorer (LLM-based auto-scoring for text answers) ---
	var scorer session.Scorer
	switch cfg.LLMProvider {
	case "gemini":
		if cfg.GoogleAIAPIKey != "" {
			scorer = openaicompat.NewAnswerScorer(
				"https://generativelanguage.googleapis.com/v1beta/openai",
				cfg.GoogleAIAPIKey,
				cfg.GeminiStructModel,
			)
			log.Printf("Answer scorer initialized: provider=gemini model=%s", cfg.GeminiStructModel)
		}
	case "anthropic":
		// TODO: implement anthropic scorer if needed
	case "mistral":
		if cfg.MistralAPIKey != "" {
			scorer = openaicompat.NewAnswerScorer(
				"https://api.mistral.ai/v1",
				cfg.MistralAPIKey,
				cfg.MistralStructModel,
			)
			log.Printf("Answer scorer initialized: provider=mistral model=%s", cfg.MistralStructModel)
		}
	case "lmstudio":
		scorer = openaicompat.NewAnswerScorer(
			cfg.LMStudioBaseURL,
			"lm-studio",
			cfg.LMStudioStructModel,
		)
		log.Printf("Answer scorer initialized: provider=lmstudio model=%s", cfg.LMStudioStructModel)
	}

	// --- Repositories (continued) ---
	examRepo := postgres.NewExamRepository(pool)

	// --- Application Services ---
	chapterSvc := app.NewChapterService(chapterRepo, masteryRepo)
	masterySvc := app.NewMasteryService(masteryRepo, publisher, clock)
	sessionSvc := app.NewSessionService(sessionRepo, chapterRepo, masteryRepo, publisher, clock, idGen, scorer)
	validationSvc := app.NewValidationService(validationRepo, chapterRepo, publisher, clock, idGen)
	onboardingSvc := app.NewOnboardingService(chapterRepo, masteryRepo, clock, idGen)
	examSvc := app.NewExamService(examRepo, publisher, clock, idGen)
	_ = examSvc // TODO: wire to handler when exam endpoints are added

	// --- Event Handlers ---
	// AttemptRecorded -> transition mastery state (connects Session → Mastery contexts).
	// Uses repo directly to avoid re-publishing AttemptRecorded (which would loop).
	dispatcher.On("attempt.recorded", func(ctx context.Context, evt event.Event) error {
		ar, ok := evt.(event.AttemptRecorded)
		if !ok {
			return nil
		}
		m, err := masteryRepo.FindByUserAndItem(ctx, ar.UserID, ar.ItemID)
		if err != nil {
			log.Printf("[event] mastery transition: mastery not found for item %s: %v", ar.ItemID, err)
			return nil
		}
		if err := m.RecordAttempt(ar.Score, clock.Now()); err != nil {
			log.Printf("[event] mastery transition failed for item %s: %v", ar.ItemID, err)
			return nil
		}
		if err := masteryRepo.Save(ctx, m); err != nil {
			log.Printf("[event] mastery save failed for item %s: %v", ar.ItemID, err)
		}
		return nil
	})

	// ExamCreated -> apply tightening to all masteries in linked chapters
	dispatcher.On("exam.created", func(ctx context.Context, evt event.Event) error {
		ec, ok := evt.(event.ExamCreated)
		if !ok {
			return nil
		}
		exam, err := examSvc.GetByID(ctx, ec.ExamID)
		if err != nil {
			log.Printf("[event] exam tightening: exam not found: %v", err)
			return nil
		}
		now := clock.Now()
		daysUntil := exam.DaysUntil(now)
		for _, chID := range ec.ChapterIDs {
			items, err := chapterRepo.FindItemsByChapter(ctx, chID, false)
			if err != nil {
				continue
			}
			for _, item := range items {
				m, err := masteryRepo.FindByUserAndItem(ctx, exam.UserID, item.ID)
				if err != nil {
					continue
				}
				m.ApplyExamTightening(daysUntil, now)
				masteryRepo.Save(ctx, m)
			}
		}
		log.Printf("[event] exam tightening applied: exam=%s days=%d chapters=%d", ec.ExamID, daysUntil, len(ec.ChapterIDs))
		return nil
	})

	// ValidationResolved -> uncap mastery CappedAtOK (Z1-AC13 complement).
	// When HITL confirms/corrects an item, the mastery cap at OK is lifted,
	// allowing the student to progress to SOLID.
	dispatcher.On("validation.resolved", func(ctx context.Context, evt event.Event) error {
		vr, ok := evt.(event.ValidationResolved)
		if !ok {
			return nil
		}
		masteries, err := masteryRepo.FindByItem(ctx, vr.ItemID)
		if err != nil {
			log.Printf("[event] validation uncap: find masteries for item %s: %v", vr.ItemID, err)
			return nil
		}
		for _, m := range masteries {
			if !m.CappedAtOK {
				continue
			}
			m.CappedAtOK = false
			m.UpdatedAt = clock.Now()
			if err := masteryRepo.Save(ctx, m); err != nil {
				log.Printf("[event] validation uncap: save mastery %s: %v", m.ID, err)
			}
		}
		log.Printf("[event] validation resolved: uncapped masteries for item %s (count=%d)", vr.ItemID, len(masteries))
		return nil
	})

	// items.generated: intentionally unhandled in Lot 0.
	// Future: could trigger ProposeEveningFirst session for the user.

	log.Println("Event dispatcher initialized with handlers: attempt.recorded, exam.created, validation.resolved")

	// --- Dev Handler (debug mode only) ---
	var devHandler *handler.Dev
	var logWriter *handler.SwitchableWriter
	if cfg.GinMode == "debug" {
		logWriter = handler.NewSwitchableWriter(os.Stdout)
		devHandler = handler.NewDev(cfg.JWTSecret, pool, onboardingSvc, cfg.MigrationsDir, logWriter)
		log.Println("Dev token endpoint enabled: GET /dev/token")
		log.Println("E2E seed endpoint enabled: POST /e2e/seed/:scenario")
	}

	// --- HTTP Handlers ---
	chapterHandler := handler.NewChapter(chapterSvc, idGen, clock)
	masteryHandler := handler.NewMastery(masterySvc)
	sessionHandler := handler.NewSession(sessionSvc)
	validationHandler := handler.NewValidation(validationSvc)
	onboardingHandler := handler.NewOnboarding(onboardingSvc)

	var pipelineHandler *handler.Pipeline
	if pipelineSvc != nil {
		pipelineHandler = handler.NewPipeline(pipelineSvc)
		log.Println("Pipeline endpoints enabled: POST /chapters/:id/upload, GET /revisions/:id/progress")
	}

	// --- Router ---
	r := apphttp.NewRouter(apphttp.RouterConfig{
		JWTSecret:         cfg.JWTSecret,
		Version:           Version,
		LogWriter:         logWriter,
		PipelineHandler:   pipelineHandler,
		ChapterHandler:    chapterHandler,
		MasteryHandler:    masteryHandler,
		SessionHandler:    sessionHandler,
		ValidationHandler: validationHandler,
		OnboardingHandler: onboardingHandler,
		DevHandler:        devHandler,
	})

	// --- HTTP server with graceful shutdown ---
	srv := &http.Server{
		Addr:    ":" + cfg.Port,
		Handler: r,
	}

	go func() {
		sigCh := make(chan os.Signal, 1)
		signal.Notify(sigCh, syscall.SIGINT, syscall.SIGTERM)
		<-sigCh
		log.Println("Shutting down...")

		shutdownCtx, shutdownCancel := context.WithTimeout(context.Background(), 10*time.Second)
		defer shutdownCancel()

		if err := srv.Shutdown(shutdownCtx); err != nil {
			log.Printf("HTTP server shutdown error: %v", err)
		}
		cancel()
	}()

	log.Printf("Starting Révise Mieux API on :%s (version %s)", cfg.Port, Version)
	if err := srv.ListenAndServe(); err != nil && err != http.ErrServerClosed {
		log.Fatalf("Server error: %v", err)
	}
}
