ALTER TABLE cours ADD COLUMN statut_ocr VARCHAR(20) NOT NULL DEFAULT 'termine';
ALTER TABLE cours ADD COLUMN pages_traitees INTEGER NOT NULL DEFAULT 0;
ALTER TABLE cours ADD COLUMN nombre_pages INTEGER NOT NULL DEFAULT 0;
ALTER TABLE cours ADD COLUMN erreur_ocr TEXT;
